### ISSUE TITLE
Settings to enable only audio  both

### ISSUE THREAD

**Issue by voidspacexyz** [ether/ep_webrtc#29]
It would be a very important feature to have the option to either enable audio or both audio + video as a plugin settings that can applied application wide.  This is useful when we want to use the system just for audio call, and not always need video.

**Comment by orblivion** [comment]
Just to make sure I don't have you wrong here: It sounds like you want one setting (let's say `"audio-only"`) that is true or false, which _completely disables_ video on the platform? By contrast, the `"enabled": false` doesn't actually disable ep_webrtc; it just makes the video/audio chat turn off _initially_ when you load a page.

**Comment by JohnMcLear** [comment]
what happens when you click disable video?  does it kill audio too?  afaik it might?

**Comment by orblivion** [comment]
BTW it seems like at this point, the solution to #23 will cover this. Let's keep an eye on #23 from here.

**Comment by JohnMcLear** [comment]
@orblivion this is interesting

> Ok... with the camera physically unplugged, but with a working microphone confirmed working live by the OS, **I do not get the "allow video.etherpad.com to use your camera and microphone"** request and the WebRTC column does not open.

> With the microphone physically disabled but with the camera plugged in, I do get the prompt and can use the camera.

**Comment by orblivion** [comment]
With what's now in `master`, based on my experience if I disable my camera and load the page it will give me a pop up error message telling me that there's no suitable camera. Did this person get that error message? (it may take a second or two)

Now, if you use my changes in #43, you can set `"video_allowed": false` in `settings.json` (i.e. admin decision), and it will only ask for microphone in the permissions prompt. I tried this with my camera disabled. Unlike before, it didn't stop me from starting a conversation (except in one version of Firefox where the microphone seemed to stay muted. Firefox is inconsistent and weird in general here.).

However, if I'm a user without a camera and the admin _hasn't_ disabled video, my changes in #43 will not let me use the "video disabled on start" feature to only request a microphone, since "disabled" in this sense is like "muted". Video should still be ready to go; you should be able to turn the camera track on with a click.

**Comment by orblivion** [comment]
Done via https://github.com/ether/ep_webrtc/pull/43 ?
