### ISSUE TITLE
line 188 of webrtc.js fires an error

### ISSUE THREAD

**Issue by JohnMcLear** [ether/ep_webrtc#66]

**Comment by orblivion** [comment]
This one is triggered if something tries to "activate" webrtc when it's already active. Was this error trivial to trigger? Did it interrupt your ability to use the site?

I did change this line, making it return a `Promise.reject()` instead of just `undefined`:

https://github.com/ether/ep_webrtc/commit/8e540972b76b7d00bd631041c9dbe1c5caa4f972

Primarily for testing purposeg, but it sort of seemed like correct behavior. However if it breaks things I can find another way to test this case.

**Comment by JohnMcLear** [comment]
I think it might be due to the settings on the clients box.



Can you replicate the error?





-----Original message-----

**Comment by orblivion** [comment]
I can replicate it by changing the code and triggering `self.activate()` when it's already active. To do it under normal circumstances would require some sort of race condition that I don't know how to trigger.

Though from the looks of it, clicking on the `listenClass` always does `activate` (unlike the enable/disable button in settings which toggles `activate` and `deactivate`). So if you have that in your setup, you could easily trigger that by clicking `listenClass` element while it's already active. We could fix this by making `listenClass` toggle, if that's the correct behavior.

**Comment by orblivion** [comment]
From trying it myself, it doesn't otherwise break the behavior of the site when this error is triggered. From what I can think of, we could either:

a) Do nothing
b) Add some text to the error so you can see in the console what is happening
c) Remove the error trigger by returning `Promise.resolve()` or `undefined` instead of the current `Promise.reject()`, and refactor the tests.

c would be returning it to what it was before I added the `Promise.reject()`.

**Comment by rhansen** [comment]
Likely fixed by recent changes.
